<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="/static/main.css" type="text/css">
</head>
<body>
<p>ФОРМА ОТПРАВКИ ЗАКАЗА</p>
<form class="decor" method="post" action="/admin_form">
    <div class="form-left-decoration"></div>
    <div class="form-right-decoration"></div>
    <div class="circle"></div>
    <div class="form-inner">
        <h3>Написать нам</h3>
        <input name="userName" type="text" placeholder="Username">
        <input type="email" placeholder="Email">
        <textarea placeholder="Сообщение..." rows="3"></textarea>
        <input type="submit" value="Отправить">
    </div>
</form>
</form>
</body>
</html>